workflows:
  version: 2.1
  jobs:
    build:    
      docker:
      - image: circleci/ruby:2.5.1-node-browsers # ruby2.5.1を利用していたため
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.6.46-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: root
          MYSQL_DATABASE: circleci-example-for-rails_test
          MYSQL_ROOT_HOST: '%'
          MYSQL_PORT: 3306
      working_directory: ~/st-connect # 処理を実行するディレクトリ
      steps: # コンテナ内で実行される処理一覧,jobsを定義する場合stepsも必須,ないとエラー発生
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.0
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
          - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Database setup
      - run:
          name: Prepare db
          command: |
            bundle exec rails db:schema:load --trace
      # run tests!
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress --color --format documentation

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results